### ISSUE TITLE
In Windows failure

### ISSUE THREAD

**Issue by liby** [wallabyjs/quokka#354]
### Issue description or question
I created a file, but quokka.js is not available. I cannot reproduce this bug now.
Now all my new files can use quokka normally. But I kept the file in error,It is still not available in this file.

### Sample code

```javascript
console.log(2);
```

### Sample repository link

[demo.zip](https://github.com/wallabyjs/quokka/files/3067546/demo.zip)

![demo](https://user-images.githubusercontent.com/38807139/55940210-3b27c500-5c72-11e9-887e-b386f519b111.gif)

### Quokka.js Console Output

```
Error: Configured file paths must be relative: c:/Users/lby/Desktop/demo.js 
at listOnTimeout (internal/timers.js:535:17) 
at processTimers (internal/timers.js:479:7)
```

### Code editor version

Visual Studio Code v1.33.0

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in v1.0.206.

**Comment by liby** [comment]
@ArtemGovorov 
What magic has been done to this file，It still doesn't work
![bug](https://user-images.githubusercontent.com/38807139/55961652-f025a600-5ca1-11e9-8a4e-bb65dc0542c5.gif)

**Comment by smcenlly** [comment]
We've found and fixed the problem. Please update to the latest version of Quokka for VS Code, v1.0.208.
