### ISSUE TITLE
Cannot run TS file - getting "require.resolve is not a function"

### ISSUE THREAD

**Issue by mostr** [wallabyjs/quokka#42]
### Issue description or question

Getting error in console when creating Typescript file in Quokka. I'm also unable to run the TS file. I'm having `typescript` installed globally for this node.js version. Creating and evaluating JS file works fine.

### Quokka.js Console Output

```
Quokka #1 (node: v6.8.0)

require.resolve is not a function
```

### Code editor version

IntelliJ 2016.3.3 EAP Build #IU-163.11103.3
### OS name and version
MacOS Sierra

**Comment by ArtemGovorov** [comment]
The issue is fixed and the fix is published in Quokka plugin v1.0.3.

**Comment by mostr** [comment]
Unfortunately, I'm on 1.0.3 already and still experiencing this issue. Tried to uninstall and reinstall it from scratch too.

**Comment by ArtemGovorov** [comment]
I can't reproduce the issue. Here's what I'm doing:

![ts](https://cloud.githubusercontent.com/assets/979966/25535449/6f2e51ae-2c7a-11e7-9144-f77e12f869c2.gif)

(note that I don't even have TypeScript installed in the project - Quokka in this case is just using its own version of TypeScript)

**Comment by ArtemGovorov** [comment]
Perhaps you could share a sample project where the issue is reproducible, along with some steps to reproduce it?

**Comment by ArtemGovorov** [comment]
Good news - we have found the way to reproduce it. The issue is fixed and the fix is published in v1.0.4.

**Comment by mostr** [comment]
Great, thanks a lot - it works fine now. But there is another thing I can't get working (not sure it's in scope of Quokka though).
I expect the following code to fail in compile time:
``` typescript
type Bar = 'a' | 'b';

function foo(a: Bar) {
  console.log(a);
}

foo('c'); // should not compile
```
while the result in console is:
```
Quokka #1 (node: v7.9.0, TypeScript: v2.1.5)

c at a quokka.ts:4:2
```

It's correct JS, but TS should prevent from compiling (or at least give me a warning that types don't match). Is there anything I do wrong?

I tried creating the scratch file both within the TS project and outside of it - still the same result.

I'm on Quokka 1.0.7.

**Comment by ArtemGovorov** [comment]
Quokka doesn't stop or report any TS compilation errors. As long as TypeScript can produce any valid JavaScript code, Quokka can run it. Type checking is out-of-scope for the tool and is a job of IDE integrated compiler.

Having said that, you may run Quokka on existing files (for example create real tmp file in your project), and IntelliJ built-in TypeScript compiler should be able to handle these cases (if your project has a valid TS configuration):

![screen shot 2017-05-02 at 4 46 57 pm](https://cloud.githubusercontent.com/assets/979966/25606899/32f872e8-2f57-11e7-9595-4d6d293b3040.png)

**Comment by ArtemGovorov** [comment]
Also see https://youtrack.jetbrains.com/issue/WEB-17352
