### ISSUE TITLE
Typescript Path/Alias broken in v1.0.260 (intellij)

### ISSUE THREAD

**Issue by dadiborn** [wallabyjs/quokka#553]
quokka-intellij-v1.0.259 was the last version that was working with TS Alias as Path Imports.
from quokka-intellij-v1.0.260 projects that was working fine before now shows error Module could not be resolved.

**Comment by smcenlly** [comment]
@dadiborn - thanks for reporting the problem. This has been fixed in the latest version of Quokka for IntelliJ, v1.0.261. The extension should become available shortly at which point in time you may upgrade to fix the issue.

**Comment by dadiborn** [comment]
> @dadiborn - thanks for reporting the problem. This has been fixed in the latest version of Quokka for IntelliJ, v1.0.261. The extension should become available shortly at which point in time you may upgrade to fix the issue.

The problem is back if we want to override some compiler options as per documentation "If you need to override some compiler options from the project’s tsconfig.json".
Looks like instead of override, Quokka does not respect projects tsconfig file and just use some internal defaults or its deep assign (if you have one) works incorrectly. Please check that part if Quokka really ***override some***.

```json
{
  "ts": {
    "compilerOptions": {
      "noImplicitAny": false
    }
  }
}
```

**Comment by ArtemGovorov** [comment]
@dadiborn Good catch, this has been fixed in the latest version of Quokka for IntelliJ, v1.0.262.
