### ISSUE TITLE
Missing Intellij icon

### ISSUE THREAD

**Issue by gabrielnemeth** [wallabyjs/quokka#569]
### Issue description or question
I'm on Intellij 2020.3 and after I start the IDE, the icon is missing. However, after I activate the plugin it appears.

![icon](https://user-images.githubusercontent.com/11211316/102634224-d49ac000-4151-11eb-909f-c42e407df55c.PNG)

![icon2](https://user-images.githubusercontent.com/11211316/102634351-001daa80-4152-11eb-812b-4096164a3af6.PNG)

### Code editor version

Intellij 2020.3

### OS name and version

Windows 10 20H2

**Comment by jorgecancinof** [comment]
I was just about to open the same issue. It's still happening to this day in IntelliJ 2022.1.

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This is fixed in Quokka for IntelliJ `v1.0.335`. Please update to the latest version, it should fix the problem.

**Comment by jorgecancinof** [comment]
It's still happening in `v1.0.335`

https://user-images.githubusercontent.com/9392099/166083561-bba063fe-c826-4b39-bcfe-72f45b3f6fe8.mp4

**Comment by smcenlly** [comment]
Thanks for letting us know. We've fixed the problem; it should now work for you correctly in `v1.0.338`+.
