### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by DmacMcgreg** [wallabyjs/quokka#82]
### Issue description or question
When importing a module written with es6 imports, I get the error message Unexpected token import

### Quokka.js file
"quokka": {
    "pro": true,
    "babel": true
  },

```javascript
import _uniq from 'lodash-es/uniq'
....

```

### Quokka.js Console Output

```
Quokka  (node: v8.4.0, babel: v6.25.0)
Unexpected token import
```

### Code editor version

Webstorm v? 2017.2.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Looks like your `.babelrc` is not set to compile ES6 modules to CommonJs.

Try this:
- clone this repo https://github.com/wallabyjs/quokka-babel-import-sample
- run `npm install`,
- start Quokka on the `quokka.js` file in the repo (open the file and start Quokka by using right click context menu option).

If the repo is working, please share a sample repo with your setup where it's not working for you.

**Comment by DmacMcgreg** [comment]
Hi there, thanks for quick response.
Here, you can see that the same error message is produced:

https://github.com/DmacMcgreg/quokka-babel-import-sample

You can replace the lodash xor method with any other method from the library and it produces the same result.

Thanks!

**Comment by ArtemGovorov** [comment]
Thanks for the repo. 

By default, babel-register ignores node modules, that's why it wasn't working for you. 
We have just published the new plugin version 1.0.31, where the support for babel `ignore` flag is added, so you may for example say: ignore all node modules but `lodash...`:

```javascript
({
  babel: {
    ignore: 'node_modules\/(?!lodash)'
  }
})
...
```

I have also sent you the [PR with the change](https://github.com/DmacMcgreg/quokka-babel-import-sample/pull/1).

**Comment by DmacMcgreg** [comment]
Just updated Quokka to latest and it is still not working.

I think there may be a bug in babel regarding ignore...

Is it working for you?

**Comment by DmacMcgreg** [comment]
Sorry to ask here, but when I add the babel-transform-runtime plugin, it seems to throw a bunch of errors. 
I know this isn't really quokka's fault, but do you know how I can disable it for quokka?
I've tried adding "plugins" : []
but that doesn't seem to work.

**Comment by DmacMcgreg** [comment]
So, using a common babel setup (vue-webpack default), I seem to be getting this error when importing an es module:

`C:/Users/dave_/Code/VueJS/tbsc-app-vue/node_modules/lodash/pull.js: BlockScoping is not a constructor (While processing preset: "\\node_modules\\babel-preset-env\\lib\\index.js") (While processing preset: "\\node_modules\\babel-preset-env\\lib\\index.js") (While processing preset: "\\node_modules\\babel-preset-env\\lib\\index.js")`

My .babelrc file is as follows:

`{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": ["transform-runtime"],
  "comments": false,
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul",
        ["transform-runtime", {
          "polyfill": false,
          "regenerator": true
        }]
      ]
    }
  }
}`

It seems like the "env" preset is the culprit. Using just "es2015" works, but this is a pretty standard setup...

Any idea what's going on here?

I can't seem to override the babelrc file with quokka either in package.json OR at the top of a file.

**Comment by ArtemGovorov** [comment]
@DmacMcgreg Could you please update your sample repo https://github.com/DmacMcgreg/quokka-babel-import-sample so that I could reproduce the configuration issue? Happy to have a look into it.

**Comment by DmacMcgreg** [comment]
@ArtemGovorov 
I have updated the package.json and .babelrc to reflect the vue-cli state
Currently when running quokka, it says "Unexpected token import"

Thank you for your help!

**Comment by ArtemGovorov** [comment]
@DmacMcgreg Did you forget to push the changes of  package.json and .babelrc to your repo https://github.com/DmacMcgreg/quokka-babel-import-sample ? I don't see any recent changes there.

**Comment by DmacMcgreg** [comment]
Looks like my commits didn't get pushed.
I updated the repo manually.

Thanks!

**Comment by ArtemGovorov** [comment]
Have sent you the PR with the config change: https://github.com/DmacMcgreg/quokka-babel-import-sample/pull/2/files. Because your `.babelrc` is using env setting, you need to set one for Quokka process (via quokka `env` setting), and don't forget the previously suggested `ignore: 'node_modules\/(?!lodash-es)'`:

```javascript
({
  env: {
    params: {
      env: "BABEL_ENV=test"
    }
  },
  babel: {
    ignore: 'node_modules\/(?!lodash-es)'
  }
})


import value from './myModule';
import _xor from 'lodash-es/xor'


console.log(_xor);
```

**Comment by DmacMcgreg** [comment]
That's really fantastic!
Thank you very much @ArtemGovorov 
Do you have a donation page? 

To anyone else who may read this, you can also set up your quokka settings within the package.json rather than putting those lines at the top of your files.

`"quokka" : {
    "pro": true,
    "babel" : {
      "ignore" : "node_modules/(?!lodash-es)"
    },
    "env": {
      "params" : {
        "env" : "BABEL_ENV=test"
      }
    }
  },`

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> Do you have a donation page?

No, but we'll soon offer the ['Pro' edition of Quokka](https://quokkajs.com/pro) (in addition to the forever free 'Community' one), so you'll be able to get yourself one if you like.
