### ISSUE TITLE
SvelteKit path alias barrel export

### ISSUE THREAD

**Issue by IwannabeRealnerD** [wallabyjs/quokka#956]
### Issue description or question

Is this issue related to Quokka not outputting the expected results of your code?: Yes

https://github.com/wallabyjs/quokka/issues/864
I had issue with alias but the issue up there helped me to fix the issue I had.
but I found out that there is another issue with SvelteKit path alias when the directory has barrel export file.

### Sample code

```javascript
// it works fine here - imported directly 
import { TEST_CONSTANT } from "./constants/testConstant";
const a = 3 + 4;

a;

TEST_CONSTANT;

// it doesn't work here - imported from barrel export file
import { TEST_CONSTANT } from "./constants";
const a = 3 + 4;

a;

TEST_CONSTANT;

```

### Sample repository link

https://github.com/IwannabeRealnerD/khanne-sh/blob/ADD-quokkajs/src/quokkaTestNotWorking.ts

### Quokka.js Console Output

```
​​​​​Quokka PRO 'quokkaTestNotWorking.ts' (node: v20.10.0, TypeScript: v5.0.4 + swc)​​​​
 
ERR_UNSUPPORTED_DIR_IMPORT <rootDir>/src/constants <rootDir>/src/quokkaTestNotWorking.js 
```

### Code editor version

Cursor Version: 0.33.4 (VSCode Version: 1.86.2)

### OS name and version

OSX

**Comment by smcenlly** [comment]
I'm assuming that you are using ESM (i.e. `"type": "module"` in your `package.json`)?

You will need to configure Quokka to run node with an option to allow importing directories with the `experimental-specifier-resolution` setting via [Quokka configuration](https://quokkajs.com/docs/configuration.html):

```json
{
  "env": {
     "params": {
        "runner": "--experimental-specifier-resolution=node"
     }
  }
}
```

**Comment by IwannabeRealnerD** [comment]
Thank you for your suggestion but it still doesn't work.

```json
{
  "env": {
     "params": {
        "runner": "--experimental-specifier-resolution=node"
     }
  }
}
```

I added this code to my .quokka.json file but it still doesn't work.

<img width="1280" alt="image" src="https://github.com/wallabyjs/quokka/assets/71207364/848ac514-d9b1-4da9-abc7-81115226654c">

**Comment by smcenlly** [comment]
We tried the `.quokka` file on a new svelte kit project and we got a slightly different error message. There was a bug in Quokka that is fixed in Quokka for VS Code `v1.0.644`.

Can you please update to the latest version of Quokka and let us know if it fixes your problem? If not, it's likely that your `.quokka` file is not located in the correct location. It should be in your project root.

**Comment by IwannabeRealnerD** [comment]
I'm afraid it still doesn't work
<img width="1181" alt="image" src="https://github.com/wallabyjs/quokka/assets/71207364/4fd9d7cf-404c-4121-bc6a-d5bdfcbeef6d">

<img width="781" alt="image" src="https://github.com/wallabyjs/quokka/assets/71207364/cf69906c-1c3c-4355-a78b-663b88926da7">

<img width="907" alt="image" src="https://github.com/wallabyjs/quokka/assets/71207364/67662cfc-1da5-4079-a539-3a1cd7dd52ea">

**Comment by smcenlly** [comment]
I've uploaded our [sample project](https://github.com/wallabyjs/quokka-957) that we originally used to reproduce your problem.

Can you please update our sample project to make it break the same way that you're seeing in your project so we can reproduce the problem?

**Comment by IwannabeRealnerD** [comment]
I reproduced the problem and updated the sample project.

<img width="1034" alt="image" src="https://github.com/wallabyjs/quokka/assets/71207364/628f883b-f6c4-4cbf-87ba-ab1829a0f601">
<img width="753" alt="image" src="https://github.com/wallabyjs/quokka/assets/71207364/3c95a77d-46a3-43ec-8f84-0f3cca66241a">

**Comment by IwannabeRealnerD** [comment]
I tried to update the sample repository but I don't have permission to push the changes.

I reproduced the problem and it turns out that if I import something from svelte, it occurs the problem.

<img width="1030" alt="image" src="https://github.com/wallabyjs/quokka/assets/71207364/904ae737-43df-4e7c-a361-8e264e050552">
<img width="760" alt="image" src="https://github.com/wallabyjs/quokka/assets/71207364/11ea46a1-1424-46ef-8aba-9803be0f392d">
<img width="954" alt="image" src="https://github.com/wallabyjs/quokka/assets/71207364/7ed788ab-002b-494c-a868-9c126af066eb">

**Comment by smcenlly** [comment]
Could you please try installing [`vite-node` to run your Quokka file](https://quokkajs.com/docs/#vite-node-runtime) instead of `node.js`? We think this may work for you as it will apply `svelte` transformations using `vite`. 

You should be able to install `vite-node` with:

```
npm install vite-node --save-dev
```

**Comment by IwannabeRealnerD** [comment]
it's finally working now! Even without .quokka file!(quokka's v1.0.644 is necessary) Thank you so much.

<img width="884" alt="image" src="https://github.com/wallabyjs/quokka/assets/71207364/d8c6be42-f40a-4dfb-be75-a16cd2696efb">

**Comment by smcenlly** [comment]
Thanks for letting us know, it's great to hear. 

There was definitely a bug in there that we fixed earlier. Seems like the rest was configuration.
